extends Node

enum STATUS{POISON, SHIELDED, BOOST}

enum PLAYER_SKILLS{SWORD, HEAL, SHIELD, COMBO}

enum HIT_FORCE{NORMAL, STRONG, CRIT}

enum UNITS{PLAYER, ENEMY}

enum BOMB_BULLET_TYPES{COUNTDOWN, COOLDOWN}

enum ENEMY_DIALOGS{SHORT, MEDIUM, LONG}
